# Generated by Django 2.0.5 on 2018-07-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Метка офиса')),
                ('city', models.CharField(max_length=128, verbose_name='Город/населенный пункт')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='Телефонама')),
                ('email', models.CharField(max_length=32, unique=True, verbose_name='Почтанама')),
                ('address', models.CharField(max_length=128, verbose_name='Полный адрес')),
            ],
        ),
    ]
