# Generated by Django 2.0.5 on 2018-08-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0002_auto_20180812_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='contact_avatars'),
        ),
    ]
