# Generated by Django 2.0.6 on 2018-08-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='возраст'),
        ),
    ]
