# Generated by Django 2.0.5 on 2018-08-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20180812_0535'),
        ('authapp', '0004_shopuser_age'),
    ]

    operations = [
    ]
